version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    restart: on-failure
    ports:
      - 15432:5432
    #TODO: .env 파일로 변경 
    environment:
      - POSTGRES_USER=acbook
      - POSTGRES_PASSWORD=acbook
      - POSTGRES_DB=acbook
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ab_net

  app-web-1:
    container_name: app-web-1
    build:
      context: ./web
      dockerfile: DockerFile.prd
    restart: "on-failure"
    hostname: localhost
    volumes:
      - ./web:/front
    environment:
      - NODE_ENV=production
      - WEB_PORT=81
    ports:
      - 81:81
    command: >
      sh -c "
      envsubst '$${WEB_PORT}' < /etc/nginx/conf.d/default-template > /etc/nginx/conf.d/default.conf &&  nginx -g 'daemon off;'
      "
    stdin_open: true
    tty: true
    networks:
      - ab_net
    depends_on:
      - app-server-1
      - app-server-2

  app-web-2:
    container_name: app-web-2
    build:
      context: ./web
      dockerfile: DockerFile.prd
    restart: "on-failure"
    hostname: localhost
    volumes:
      - ./web:/front
    environment:
      - NODE_ENV=production
      - WEB_PORT=82
    ports:
      - 82:82
    command: >
      sh -c "
      envsubst '$${WEB_PORT}' < /etc/nginx/conf.d/default-template > /etc/nginx/conf.d/default.conf &&  nginx -g 'daemon off;'
      "
    stdin_open: true
    tty: true
    networks:
      - ab_net
    depends_on:
      - app-server-1
      - app-server-2


  app-server-1:
    container_name: app-server-1
    build:
      context: ./server
      dockerfile: DockerFile.prd
    restart: on-failure
    volumes:
      - ./server:/back
      - /back/.gradle
      - /back/build
    ports: 
      - 10001:22
    working_dir: /back
    environment:
      - SPRING_PROFILES_ACTIVE=prd
      - WAS_PORT=8081
      - VERSION=1.0
    entrypoint: ["/entrypoint.sh"]
    networks:
      - ab_net
    depends_on:
      - postgres

  app-server-2:
    container_name: app-server-2
    image: gradle:6.9.2-jdk11-alpine
    restart: on-failure
    volumes:
      - ./server:/back
      - /back/.gradle
      - /back/build
    working_dir: /back
    environment:
      - SPRING_PROFILES_ACTIVE=prd
      - WAS_PORT=8082
      - VERSION=1.0
    command: >
      sh -c "cd /back && gradle bootJar && java -jar build/libs/server-1.0.jar"
    networks:
      - ab_net
    depends_on:
      - postgres 
  
  nginx: 
    container_name: nginx
    image: nginx:stable-alpine
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: >
      sh -c "nginx -g \"daemon off;\""
    ports:
      - 80:80
    depends_on:
      - app-web-1  
      - app-web-2  
    networks:
      - ab_net

networks: 
  ab_net:
    driver: bridge
