version: "3.3"

services:

  # POSTGRES 컨테이너 : S
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine3.18 # 버전 고정 (psql 15.3)
    restart: on-failure
    ports:
      - 15432:5432
    #TODO: .env 파일로 변경
    environment:
      - POSTGRES_USER=acbook
      - POSTGRES_PASSWORD=acbook
      - POSTGRES_DB=acbook
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ab_net
  # POSTGRES 컨테이너 : E

  # FRONT (Vue.js) 컨테이너 : S
  # 빌드는 web/DockerFile.prd 보면 build-stage에서 node.js 컨테이너 생성 후 yarn build로 빌드. 후에 nginx 컨테이너를 불러와 리소스 복사
  app-web-1: &app-web
    container_name: app-web-1
    build:
      context: ./web
      dockerfile: DockerFile.prd  
    restart: "on-failure"
    hostname: localhost
    volumes:
      - ./ssh:/root/.ssh
    environment:
      - NODE_ENV=production
      - WEB_PORT=81
    ports:
      - 10001:22
      - 81:81
    entrypoint: ["/entrypoint.sh"]
    stdin_open: true
    tty: true
    networks:
      - ab_net
    depends_on:
      - app-server-1
      - app-server-2

  app-web-2:
    <<: *app-web
    container_name: app-web-2
    ports:
      - 10002:22
      - 82:81
    environment:
      - WEB_PORT=82
    depends_on:
      - app-server-1
      - app-server-2
  # FRONT (Vue.js) 컨테이너 : E
    
  # BACK (Spring boot) 컨테이너 : S
  # /upload 디렉토리는 업로드되어있는 파일들이 모여있는 디렉토리.
  # /upload 디렉토리는 로컬 PC에 저장되며 이 디렉토리는 각 Backend 컨테이너에 마운트 되어있음
  app-server-1: &app-server
    container_name: app-server-1
    build:
      context: ./server
      dockerfile: DockerFile.prd
    restart: on-failure
    volumes:
      - ./ssh:/root/.ssh
      - ./upload:/upload
    ports:
      - 20001:22
    working_dir: /back
    environment:
      - SPRING_PROFILES_ACTIVE=prd
      - WAS_PORT=8081
      - VERSION=1.0
    entrypoint: ["/entrypoint.sh"]
    networks:
      - ab_net
    depends_on:
      - postgres

  app-server-2:
    <<: *app-server
    container_name: app-server-2
    ports:
      - 20002:22
    environment:
      - WAS_PORT=8082
    depends_on:
      - postgres
  # BACK (Spring boot) 컨테이너 : E
    
  # NginX 컨테이너 : S
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.prd
    volumes:
      - ./ssh:/root/.ssh
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    entrypoint: ["/entrypoint.sh"]
    ports:
      - 80:80
    depends_on:
      - app-web-1
      - app-web-2
    networks:
      - ab_net
  # NginX 컨테이너 : E

  # Jenkins 실행
  # 해당 Jenkins는 Docker hub에 있는 공식 이미지가 아닌, 직접 만든 이미지로, 해당 이미지를 다운받기 위해서 관리자에게 docker hub ID/PW를 받아야함.
  jenkins:
    container_name: ab-jenkins
    image: jiseok1378/ab-jenkins:latest
    restart: on-failure
    ports:
      - 20000:8080
    networks:
      - ab_net
    volumes:
      - ./build-script:/var/lib/jenkins/build-script
    command: >
      sh -c "chmod 777 /var/lib/jenkins/build-script/* &&
      rm /var/lib/jenkins/.ssh/known_hosts &&
      echo "$$(ssh-keyscan -t rsa,dsa github.com)" >> /var/lib/jenkins/.ssh/known_hosts &&
      service ssh restart &&
      service jenkins restart &&
      tail -f /var/log/jenkins/jenkins.log"

networks:
  ab_net:
    driver: bridge
