version: '3.3'

volumes:
  dev_db:
  media-data-volume: 

services:
  postgres:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    #TODO: .env 파일로 변경 
    environment:
      - POSTGRES_USER=acbook
      - POSTGRES_PASSWORD=acbook
      - POSTGRES_DB=acbook
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-sql/init.sql:/docker-entrypoint-initdb.d/init.sql
