FROM node:18.16

ENV HOST=0.0.0.0
ENV CHOKIDAR_USEPOLLING=true
ENV PATH /front/node_modules/.bin:$PATH

RUN apt-get update \ 
    # && apt-get install -y openssh-server nano vim sudo curl zip \
    && rm -rf /var/lib/apt/list/*

RUN npm install -g @vue/cli

# RUN curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -

# RUN apt-get install -y nodejs \ 
    # && rm -rf /var/lib/apt/list/*

# RUN npm install -g yarn

# RUN service ssh start

WORKDIR /front

COPY package*.json /front

RUN yarn install

EXPOSE 8080

COPY . /front

ENTRYPOINT ["yarn", "serve"]